# ai-hub-platform.spec
# Generated by PyInstaller: DO NOT EDIT THIS FILE MANUALLY!

# -*- mode: python ; coding: utf-8 -*-

block_cipher = None


a = Analysis(
    ['desktop_app.py'],
    pathex=['E:\\AI Function Library\\OpenSource\\ai-hub-platform'],
    binaries=[],
    datas=[
        ('web\\*', 'web'),
        ('core\\*', 'core'),
        ('docs\\*', 'docs'),
        ('tests\\*', 'tests'),
        ('*.md', '.'),
        ('LICENSE', '.'),
        ('requirements.txt', '.'),
    ],
    hiddenimports=[
        'tkinter',
        'tkinter.ttk',
        'tkinter.scrolledtext',
        'tkinter.messagebox',
        'tkinter.filedialog',
        'queue',
        'threading',
        'pathlib',
        'os',
        'sys',
    ],
    hookspath=[],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    win_no_prefer_redirects=False,
    win_private_assemblies=False,
    cipher=block_cipher,
    noarchive=False,
)
pyz = PYZ(a.pure, a.zipped_data,
          cipher=block_cipher)

exe = EXE(
    pyz,
    a.scripts,
    a.binaries,
    a.zipfiles,
    a.datas,
    [],
    name='AIHub',
    debug=False,
    bootloader_ignore_signals=False,
    strip=False,
    upx=True,
    upx_exclude=[],
    runtime_tmpdir=None,
    console=False,  # Set to False for GUI app (no console window)
    disable_windowed_traceback=False,
    target_arch=None,
    codesign_identity=None,
    entitlements_file=None,
)
coll = COLLECT(
    exe,
    a.binaries,
    a.zipfiles,
    a.datas,
    strip=False,
    upx=True,
    upx_exclude=[],
    name='AIHub',
)